### ISSUE TITLE
Blasta and XMPP as a platform to synchronize bookmarks

### ISSUE THREAD

**Issue by sjehuda** [asciimoo/omnom#19]
Good day, Adam!

This message is about XMPP, and PEP and PubSub as means to manage and synchronize bookmarks.

[Libervia](https://libervia.org/), [Movim](https://movim.eu/), and [Rivista](https://git.xmpp-it.net/sch/Rivista) are publishing platforms that do not host any content on their own, and rather read Atompub/Atomsub PubSub nodes of XMPP accounts and services of XMPP server.

On the same premise, we have created Blasta, which makes use of PubSub as a platform to manage and synchronize bookmarks.

Blasta is a collaborative bookmarks system which makes use of XMPP as a platform https://git.xmpp-it.net/sch/Blasta

Omnom is mentioned at page "Similar Projects" https://git.xmpp-it.net/sch/Blasta/src/branch/main/xhtml/projects.xhtml

**Comment by asciimoo** [comment]
Thank you for mentioning Omnom. I'm open to add XMPP support to Omnom if there is high enough interest in this feature.

**Comment by sjehuda** [comment]
I suppose it is a valid feature, because it is working; and, I also
suppose that the interest is definitely more than enough.

I know people who state that they would be more available on XMPP, if
there woluld be even more people.

This issue can be solved by adding XMPP support, and consequently earn
more presence of people in it.

I would advise you to visit group chats JDev, Modern XMPP, Berlin XMPP
Meetup, and you would see the amount of new people, and also talk to
experienced people who lead some popular XMPPP projects.

Search for a group chat at https://search.jabber.network/

You can try Blasta on your own machine or even a public instance
at https://blasta.woodpeckersnest.eu/

**Comment by sjehuda** [comment]
I urge you not to wait; and, I further urge you to try it for yourself.

Please watch my videos at: https://video.xmpp-it.net/c/sch/videos (each is less than 8 minutes).

I am also working on a Falkon extension for Blasta https://github.com/jarun/buku/discussions/772

If the practice is working (i.e. proven to be effective), then I will implement it.

---

Generally, when I raise Jabber/XMPP, even some developers immediately shun the idea, because some people associate XMPP only with instant messaging, yet it is not so.

The fact is, that XMPP is already advanced enough to be able to replace all of HTML browsers with XMPP alone, even for video games.

XMPP even has a specification for [Data Form interface](https://git.xmpp-it.net/sch/Slixfeed#preview), which is something that W3C could have done for HTML and ECMA too, but chose not to do so, probably due to pressure from HTML browser vendors.

XMPP has Data Forms and ECMA has a pop up with a single button, which is activated with `alert()`.

---

This is an interesting quote from an article which was published by DIVA.EXCHANGE, about the need to consider other use-cases of a technology of type, in order to have more people to use the technology.

> New technologies are ahead of the ability of ordinary people to understand and use them.

> Technology is extremely powerful and has the potential to change the world; however, it cannot realize its full potential unless people feel the need to use it.

> Some researchers agree that to ensure the success of new technology, the focus should be on the user’s perspective rather than the technology itself.

> Designing a new experience is a process that facilitates the relationship between technology and people; thus, balanced research should be conducted from both perspectives. When applying a new technology, developers should give equal importance to the UX design strategy and the development method.

From: https://www.diva.exchange/en/privacy/trust-in-the-cryptocurrency-economy-resolving-the-problem-experience-of-diva-exchange-part-2/

**Comment by sjehuda** [comment]
I have another argument, and I advise to consider the "push" capabilities of XMPP, and also the time of which it was posted (September 9th, 2008).

### Argument 1

> Maybe some more thoughts about why I think XMPP is the way to go:

> * Microblogging is not only logging thoughts etc to a db. It’s about communication. And it’s about communication with focus on NOW. So we need real time capabilities back. twitter has failed on this.

> * Polling sucks. Microblogging should be more like chatting. Maybe an initial tweet is often a starting point for various conversations. Polling with limited requests per hour spoils these oportunities. Polling a REST API may be just fine for integrating your content with your own web site or for synchronising with other social networks but not for real time communication.
  
> * Microblogging is a service for the real masses - **they just don’t know yet**. Doesn’t seem as if twitter could handle this if it’d be really adopted by the masses. It’s a matter of scalability.

> * And if it’s for the masses we need decentralization.

> * And interoperability. Sth. twitter has great success with - a challenge for us.

> There’s been so much conversation on this topic. Conferences are being held and so on. But actually I think it’s time to not only talk about it. Face it! Get your hands dirty!

### Argument 2

I have made another argument about developers DO and people SHOW. The developers are the enablers.

https://github.com/psi-im/psi/issues/870#issuecomment-3172470272

### Argument 3

And, I will send to you another resource, in private.
